from fastapi import FastAPI, Form
from fastapi.middleware.cors import CORSMiddleware
from google import genai
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("API_KEY")

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

client = genai.Client(api_key=api_key)

@app.post("/prompt")
async def generate_url(
    prompt: str = Form(...),
    lang: str = Form("en")
):
    if lang == "th":
        modprompt = (
            f"ตรวจสอบว่าข่าวนี้เป็นข่าวปลอมหรือไม่ "
            f"ให้ผลลัพธ์เป็น true หรือ false ตามด้วยเครื่องหมายจุลภาคและเปอร์เซ็นต์ความแม่นยำ "
            f"จากนั้นตามด้วยเหตุผล เช่น: false,98,รัฐบาลได้ยืนยันแล้วว่าเป็นข่าวจริง: {prompt}"
        )
    else:
        modprompt = (
            f"Check if this news fake. "
            f"Output true or false, followed by a comma and accuracy percentage and then reason. "
            f"(eg: false,98,the goverments has confirm this.): {prompt}"
        )
    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=modprompt,
    )
    raw_text = response.text.strip()
    parts = raw_text.split(",", 2)
    if len(parts) == 3:
        result = parts[0].strip().lower() == "true"
        try:
            accuracy = int(parts[1].strip())
        except ValueError:
            accuracy = None
        reason = parts[2].strip()
        return {
            "result": result,
            "accuracy": accuracy,
            "reason": reason,
            "lang": lang
        }
    else:
        return {"raw_output": raw_text}

@app.post("/url")
async def generate_url(
    url: str = Form(...),
    lang: str = Form("en")
):
    if lang == "th":
        modprompt = (
            f"ตรวจสอบว่า URL นี้เป็นภาพที่สร้างโดย AI หรือไม่ "
            f"ให้ผลลัพธ์เป็น true หรือ false ตามด้วยเครื่องหมายจุลภาคและเปอร์เซ็นต์ความแม่นยำ "
            f"จากนั้นตามด้วยเหตุผล เช่น: false,98,ภาพนี้ถูกสร้างโดย AI เพราะมีแสงที่ไม่สมจริง: {url}"
        )
    else:
        modprompt = (
            f"Check if this image in URL is generated by AI. "
            f"Output true or false, followed by a comma and accuracy percentage and then reason. "
            f"(eg: false,98,this image was generated by AI because it has unrealistic lighting): {url}"
        )
    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=modprompt,
    )
    raw_text = response.text.strip()
    parts = raw_text.split(",", 2)
    if len(parts) == 3:
        result = parts[0].strip().lower() == "true"
        try:
            accuracy = int(parts[1].strip())
        except ValueError:
            accuracy = None
        reason = parts[2].strip()
        return {
            "result": result,
            "accuracy": accuracy,
            "reason": reason,
            "lang": lang
        }
    else:
        return {"raw_output": raw_text}
