from fastapi import FastAPI, Form
from fastapi.middleware.cors import CORSMiddleware
from google import genai
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("API_KEY")

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

client = genai.Client(api_key=api_key)

@app.post("/prompt")
async def generate_prompt(prompt: str = Form(...)):
    modprompt = (
        f"Check if this news fake. "
        f"Output true or false, followed by a comma and accuracy percentage and then reason. "
        f"(eg: false,98,the goverments has confirm this.): {prompt}"
    )
    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=modprompt,
    )
    raw_text = response.text.strip()
    parts = raw_text.split(",", 2)
    if len(parts) == 3:
        result = parts[0].strip().lower() == "true"
        try:
            accuracy = int(parts[1].strip())
        except ValueError:
            accuracy = None
        reason = parts[2].strip()
        return {
            "result": result,
            "accuracy": accuracy,
            "reason": reason
        }
    else:
        return {"raw_output": raw_text}

@app.post("/url")
async def generate_url(url: str = Form(...)):
    modprompt = (
        f"Check if this image in URL is generated by AI. "
        f"Output true or false, followed by a comma and accuracy percentage and then reason. "
        f"(eg: false,98,this image was generated by AI because it has unrealistic lighting): {url}"
    )
    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=modprompt,
    )
    raw_text = response.text.strip()
    parts = raw_text.split(",", 2)
    if len(parts) == 3:
        result = parts[0].strip().lower() == "true"
        try:
            accuracy = int(parts[1].strip())
        except ValueError:
            accuracy = None
        reason = parts[2].strip()
        return {
            "result": result,
            "accuracy": accuracy,
            "reason": reason
        }
    else:
        return {"raw_output": raw_text}
