from google import genai
import os
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.
api_key = os.getenv("API_KEY")
db_password = os.getenv("DB_PASSWORD")

client = genai.Client(api_key="AIzaSyB4ccEW4IKSXVfsaO4eqoURQodpzLWRuLc")

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbCIG-uh8I0Z_ACfbbokG8fKSOtWyXP8xqggfSEA6wg&s is this image generated by ai? reply with true or false then the reasoning then show the accuracies in percentage",
)

print(response.text)